---

- hosts: all
  become: true
  tasks:

  - name: yum update packages
    yum:
      name: '*'
      state: latest
    when: ansible_distribution == "OracleLinux"
  

  - name: uninstall apache httpd service
    yum:
      name: httpd
      state: absent
    when: ansible_distribution == "OracleLinux"
